#!groovy

// Generated by IBM TransformationAdvisor
// Tue Jun 25 15:33:12 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}